# This is the Azure Pipelines configuration is also used to create the
# precompiled release archives that are made available at <https://rakudo.org>.
#
# To trigger a build, go to <https://dev.azure.com/infra0037/raku/...> and
# manually start a run of this pipeline.
#
# The following pipeline variables are required:
#
# BUILD_PRECOMP_RELEASE: Set this to "yes".
# RELEASE_URL: Release archive to build. e.g. "https://rakudo.org/dl/rakudo/rakudo-2020.05.tar.gz"
# VERSION: The version that you are building. e.g. "2020.05"
# REVISION: Usually "01"
#

trigger:
- main

pr:
- main

variables:
  # Turn this Powershell console into a developer powershell console.
  # https://intellitect.com/enter-vsdevshell-powershell/
  PWSH_DEV: |
    $installPath = &"C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -latest -property installationpath
    $devShellLoadedSuccess = $false
    if (Test-Path -Path ../where_is_devshell/here.txt -PathType leaf) {
      $tryDevShell = Get-Item -Path ../where_is_devshell/here.txt | Get-Content -Head 1
      if (Test-Path -Path $tryDevShell) {
        try {
          Import-Module $tryDevShell
          $devShell = $tryDevShell
          $devShellLoadedSuccess = $true
          Write-Output "Successfully loaded DevShell.dll from $tryDevShell"
        }
        catch {
          Write-Output "##[warning]While trying to load the devShell module from $tryDevShell"
          Write-Output $_
        }
      }
    }
    if (-not $devShellLoadedSuccess) {
      Write-Output "Locating DevShell.dll in visual studio installation, please hold on ..."
      $devShell = &"C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -latest -find **\Microsoft.VisualStudio.DevShell.dll
      Write-Output "Found DevShell.dll at $devShell"
      try {
        mkdir ../where_is_devshell/
        $devShell | out-file -filepath ../where_is_devshell/here.txt
      }
      catch {
        Write-Output "##[warning]Couldn't cache $devShell in ../where_is_devshell/here.txt :("
        Write-Output $_
      }
      Import-Module $devShell
    }
    Enter-VsDevShell -VsInstallPath $installPath -SkipAutomaticLocation -DevCmdArguments "-arch=amd64"
  RAKUDO_CHECKOUT_TYPE: "rev-$(Build.SourceVersion)-selfrepo"
  NQP_CHECKOUT_TYPE: downstream
  MOAR_CHECKOUT_TYPE: downstream

parameters:
- name: backends
  type: object
  default: ['JVM', 'MVM']
- name: variant
  type: object
  default: ['relocatable', 'fullspectest', '']
- name: oses
  type: object
  default: ['Win', 'Lin', 'Mac']


stages:
- stage: Test
  condition: ne( variables['BUILD_PRECOMP_RELEASE'], 'yes' )

  jobs:
  - ${{ each backend in parameters.backends }}:
    - ${{ each variant in parameters.variant }}:
      - ${{ each os in parameters.oses }}:
        - job: ${{ os }}${{ backend }}${{ variant }}
          variables:
          - name: BACKEND
            value: ${{ backend }}
          - name: RELOCATABLE
            ${{ if eq(variant, 'relocatable') }}:
              value: "yes"
            ${{ if ne(variant, 'relocatable') }}:
              value: ""
          - name: SPECTEST_ONLY
            ${{ if eq(variant, 'fullspectest') }}:
              value: "yes"
            ${{ if ne(variant, 'fullspectest') }}:
              value: ""
          - ${{ if eq(backend, 'JVM') }}:
            - name: NQP_OPTIONS
              value: '--backends=jvm'
            - name: RAKUDO_OPTIONS
              value: '--backends=jvm'
          - ${{ if and( eq(backend, 'MVM'), eq(variant, 'relocatable') ) }}:
            - name: NQP_OPTIONS
              value: '--backends=moar --relocatable'
            - name: RAKUDO_OPTIONS
              value: '--backends=moar --relocatable'
            - name: MOAR_OPTIONS
              value: '--relocatable'
          - ${{ if and( eq(backend, 'MVM'), ne(variant, 'relocatable') ) }}:
            - name: NQP_OPTIONS
              value: '--backends=moar'
            - name: RAKUDO_OPTIONS
              value: '--backends=moar'
          - ${{ if eq(os, 'Win') }}:
            - name: IMAGE_NAME
              value: 'windows-2019'
            - name: IS_WIN
              value: true
          - ${{ if eq(os, 'Lin') }}:
            - name: IMAGE_NAME
              value: 'ubuntu-20.04'
            - name: IS_WIN
              value: false
          - ${{ if eq(os, 'Mac') }}:
            - name: IMAGE_NAME
              value: 'macOS-12'
            - name: IS_WIN
              value: false

          # on JVM, only do the "nothing" variant:
          # - too slow for spectest
          # - relocatable does not apply
          # also: only run fullspectest on linux for now
          condition: |
            and(
              or( eq( variables.variant, '' ),
                  ne( variables.BACKEND, 'JVM' )
              ),
              or( ne( variables.os, 'Lin'),
                  ne( variables.variant, 'fullspectest' )
              )
            )

          pool:
            vmImage: $(IMAGE_NAME)
          workspace:
            clean: all
          timeoutInMinutes: 180
          steps:
          - ${{ if eq(os, 'Win') }}:
            - pwsh: |
                # Windows has a maximum PATH variable length of 2048 (depending on
                # how it's accessed). The length of PATH in AzureCI is already
                # really tight. We'll run into the limit when we add Java and the
                # MS BuildTools to the path.
                # To work around this, we remove a bunch of stuff we won't need
                # from PATH here.
                $shortened_path = "$(PATH)" -replace ';[^;]*(SeleniumWebDrivers|SQL Server|Mercurial|Amazon|mysql|\\sbt\\|NSIS|Windows Performance Toolkit|php|Subversion)[^;]*(?=(;|$))', ''
                echo "##vso[task.setvariable variable=PATH]$shortened_path"
              displayName: "Shorten PATH on Windows"
            - pwsh: |
                echo "##vso[task.setvariable variable=JAVA_HOME]$(JAVA_HOME_11_X64)"
                echo "##vso[task.setvariable variable=PATH]$(JAVA_HOME_11_X64)\bin;$(PATH)"
              displayName: "Set java version (Windows)"
              enabled: ${{ eq(backend, 'JVM') }}

          - ${{ if and(ne(os, 'Win'), eq(backend, 'JVM')) }}:
            - script: |
                echo "##vso[task.setvariable variable=JAVA_HOME]$(JAVA_HOME_11_X64)"
                echo "##vso[task.setvariable variable=PATH]$(JAVA_HOME_11_X64)/bin:$(PATH)"
              displayName: "Set java version (non-Windows)"

          - checkout: self
            path: selfrepo
            displayName: Checkout script repo

          - bash: |
              export IS_AZURE_PIPELINES_BUILD=1
              echo "##[task.setvariable variable=IS_AZURE_PIPELINES_BUILD]1"
            displayName: "set IS_AZURE_PIPELINES_BUILD to 1"

          - script: perl selfrepo/tools/build/checkout-repos-for-test.pl $(RAKUDO_CHECKOUT_TYPE) $(NQP_CHECKOUT_TYPE) $(MOAR_CHECKOUT_TYPE)
            workingDirectory: $(Pipeline.Workspace)
            enabled: ${{ eq(backend, 'MVM') }}
            displayName: Checkout repositories (MoarVM)
          - script: perl selfrepo/tools/build/checkout-repos-for-test.pl $(RAKUDO_CHECKOUT_TYPE) $(NQP_CHECKOUT_TYPE) none
            workingDirectory: $(Pipeline.Workspace)
            enabled: ${{ eq(backend, 'JVM') }}
            displayName: Checkout repositories (JVM)

          - ${{ if eq(os, 'Win') }}:
            - task: Cache@2
              displayName: "load cached location of devshell dll"
              inputs:
                key: '"where is devshell on" | "$(IMAGE_NAME)"'
                path: ../where_is_devshell/

          - ${{ ne(backend, 'JVM') }}:
            - bash: |
                MOAR_REV=$(cd MoarVM; git describe --always)
                echo "##vso[task.setvariable variable=moar_git_rev]"$MOAR_REV
                echo moarvm repository has $MOAR_REV checked out
                NQP_REV=$(cd nqp; git describe --always)
                echo "##vso[task.setvariable variable=nqp_git_rev]"$NQP_REV
                echo nqp repository has $NQP_REV checked out
                echo "##vso[build.addbuildtag]moar-rev-"$MOAR_REV
                echo "##vso[build.addbuildtag]nqp-rev-"$NQP_REV
              displayName: "Get moar & nqp revision"
              workingDirectory: '$(Pipeline.Workspace)/'
            
          - ${{ eq(backend, 'JVM') }}:
            - bash: |
                NQP_REV=$(cd nqp; git describe --always)
                echo "##vso[task.setvariable variable=nqp_git_rev]"$NQP_REV
                echo nqp repository has $NQP_REV checked out
                echo "##vso[build.addbuildtag]nqp-rev-"$NQP_REV
              displayName: "Get nqp revision (jvm)"
              workingDirectory: '$(Pipeline.Workspace)/'

          - task: Cache@2
            displayName: "load cached NQP-m & moar"
            inputs:
              key: 'v2 | "$(BACKEND)" | "$(MOAR_CHECKOUT_TYPE)" | "$(MOAR_OPTIONS)" | "$(IMAGE_NAME)" | "$(moar_git_rev) + $(nqp_git_rev)" | "$(NQP_CHECKOUT_TYPE)" | "$(NQP_OPTIONS)"'
              path: ../install-nqp-and-moar
              cacheHitVar: NQP_CACHE_RESTORED

          - bash: |
              mkdir ../install
              cp -r ../install-nqp-and-moar/* ../install/
            displayName: "extract nqp-and-moar cache"
            condition: eq( variables['NQP_CACHE_RESTORED'], 'true' )

          - ${{ if ne(backend, 'JVM') }}:
            - task: Cache@2
              displayName: "load cached moarvm"
              inputs:
                key: '3 | "$(MOAR_CHECKOUT_TYPE)" | "$(MOAR_OPTIONS)" | "$(IMAGE_NAME)" | "$(moar_git_rev)"'
                path: ../install-moar
                cacheHitVar: MOARVM_CACHE_RESTORED
              condition: ne( variables['NQP_CACHE_RESTORED'], 'true' )

          - bash: |
              mkdir ../install
              cp -r ../install-moar/* ../install/
            displayName: "extract moar cache"
            condition: eq( variables['MOARVM_CACHE_RESTORED'], 'true' )

          - ${{ if ne(backend, 'JVM') }}:
            # Build MoarVM
            - ${{ if ne(os, 'Win') }}:
              - script: |
                  perl Configure.pl --prefix=../install $(MOAR_OPTIONS)
                  make install && cp -r ../install ../install-moar
                workingDirectory: '$(Pipeline.Workspace)/MoarVM'
                condition: and(succeeded(), ne( variables['MOARVM_CACHE_RESTORED'], 'true' ), ne( variables['NQP_CACHE_RESTORED'], 'true' ) )
                displayName: Build MoarVM
            - ${{ if eq(os, 'Win') }}:
              - pwsh: |
                  ${{ variables.PWSH_DEV }}
                  perl Configure.pl --prefix=..\install $(MOAR_OPTIONS)
                  nmake install && cp -r ../install ../install-moar
                failOnStderr: false
                workingDirectory: '$(Pipeline.Workspace)/MoarVM'
                condition: and(succeeded(), ne( variables['MOARVM_CACHE_RESTORED'], 'true' ), ne( variables['NQP_CACHE_RESTORED'], 'true' ) )
                displayName: Build MoarVM (Windows)

          # Build NQP
          - ${{ if ne(os, 'Win') }}:
            - script: |
                perl Configure.pl --prefix=../install $(NQP_OPTIONS)
                make install && cp -r ../install ../install-nqp-and-moar
              workingDirectory: '$(Pipeline.Workspace)/nqp'
              condition: and(succeeded(), ne( variables['NQP_CACHE_RESTORED'], 'true') )
              enabled: ${{ ne(os, 'Win') }}
              displayName: Build NQP
          - ${{ if eq(os, 'Win') }}:
            - pwsh: |
                ${{ variables.PWSH_DEV }}
                perl Configure.pl --prefix=..\install $(NQP_OPTIONS)
                nmake install && cp -r ../install ../install-nqp-and-moar
              failOnStderr: false
              workingDirectory: '$(Pipeline.Workspace)/nqp'
              condition: and(succeeded(), ne( variables['NQP_CACHE_RESTORED'], 'true'))
              displayName: Build NQP (Windows)

          - ${{ if ne( backend, 'JVM' ) }}:
            # Build Rakudo
            - ${{ if ne(os, 'Win') }}:
              - script: |
                  perl Configure.pl --prefix=../install $(RAKUDO_OPTIONS)
                  make install
                workingDirectory: '$(Pipeline.Workspace)/rakudo'
                displayName: Build Rakudo
            - ${{ if eq(os, 'Win') }}:
              - pwsh: |
                  ${{ variables.PWSH_DEV }}
                  perl Configure.pl --prefix=..\install $(RAKUDO_OPTIONS)
                  nmake install
                failOnStderr: false
                workingDirectory: '$(Pipeline.Workspace)/rakudo'
                displayName: Build Rakudo (Windows)

            - ${{ if eq(variant, 'relocatable' }}:
              # TODO: Should use "install moved" instead of "install-moved". But `prove` currently fails with an executable path that contains a space.
              - script: mv install install-moved
                workingDirectory: $(Pipeline.Workspace)
                displayName: Move installation
                enabled: ${{ ne(os, 'Win') }}
              - pwsh: mv install install-moved
                workingDirectory: $(Pipeline.Workspace)
                displayName: Move installation (Windows)
                enabled: ${{ eq(os, 'Win') }}

          - ${{ if ne( backend, 'JVM' ) }}:
            # Test Rakudo
            - ${{ if eq(os, 'Win') }}:
              - pwsh: |
                  ${{ variables.PWSH_DEV }}
                  prove -e ..\install\bin\perl6 -vlr t
                workingDirectory: '$(Pipeline.Workspace)/rakudo'
                enabled: ${{ ne( variant, 'relocatable' ) }}
                displayName: Test Rakudo (Windows)
              - pwsh: |
                  ${{ variables.PWSH_DEV }}
                  prove -e ..\install-moved\bin\perl6 -vlr t
                workingDirectory: '$(Pipeline.Workspace)/rakudo'
                enabled: ${{ eq( variant, 'relocatable' ) }}
                displayName: Test Rakudo (relocated, Windows)

            - ${{ if ne(os, 'Win') }}:
              - script: prove -e ../install/bin/perl6 -vlr t
                workingDirectory: '$(Pipeline.Workspace)/rakudo'
                enabled: ${{ eq( variant, '' ) }}
                displayName: Test Rakudo
              - script: prove -e ../install-moved/bin/perl6 -vlr t
                workingDirectory: '$(Pipeline.Workspace)/rakudo'
                enabled: eq( variant, 'relocatable' ) )
                displayName: Test Rakudo (relocated)
  
          - ${{ if ne( backend, 'JVM' ) }}:
            # Run spectest
            - ${{ if and(eq( variant, 'fullspectest' ), ne(os, 'Win')) }}:
              - script: make TEST_JOBS=2 m-spectest
                workingDirectory: '$(Pipeline.Workspace)/rakudo'
                displayName: Run spectest

            - ${{ if eq(variant, 'relocatable') }}:
              - publish: $(Pipeline.Workspace)/install-moved
                displayName: Publish build artifact

- stage: Build_Precomp_Release
  condition: eq( variables['BUILD_PRECOMP_RELEASE'], 'yes' )
  jobs:
    - job: linux
      displayName: Linux x86_64 build
      pool:
        vmImage: 'ubuntu-20.04'
      container:
        image: centos:7
        options: "--name raku-build-container -v /usr/bin/docker:/tmp/docker:ro"
      workspace:
        clean: all
      steps:
        - script: |
            /tmp/docker exec -t -u 0 raku-build-container sh -c 'sed -i s/mirror.centos.org/vault.centos.org/g /etc/yum.repos.d/*.repo'
            /tmp/docker exec -t -u 0 raku-build-container sh -c 'sed -i s/^#.*baseurl=http/baseurl=http/g /etc/yum.repos.d/*.repo'
            /tmp/docker exec -t -u 0 raku-build-container sh -c 'sed -i s/^mirrorlist=http/#mirrorlist=http/g /etc/yum.repos.d/*.repo'
          displayName: Work around mirrorlist.centos.org being discontinued

        - script: /tmp/docker exec -t -u 0 raku-build-container sh -c "yum -y update && yum -y install sudo"
          displayName: Set up sudo (see https://github.com/microsoft/azure-pipelines-agent/issues/2043)

        - checkout: self
          path: source
          displayName: Checkout repository

        - script: $(Agent.BuildDirectory)/source/tools/build/binary-release/build-linux.sh
          failOnStderr: false
          displayName: Run build script

        - publish: rakudo-linux.tar.gz
          artifact: rakudo-linux

    - job: macos
      displayName: MacOS x86_64 build
      pool:
        vmImage: 'macOS-12'
      workspace:
        clean: all
      steps:
        - checkout: self
          path: source

        - script: $(Agent.BuildDirectory)/source/tools/build/binary-release/build-macos.sh
          failOnStderr: false
          displayName: Run build script

        - publish: rakudo-macos.tar.gz
          artifact: rakudo-macos

    - job: windows
      displayName: Windows x86_64 build
      pool:
        vmImage: 'windows-2019'
      workspace:
        clean: all
      steps:
        - checkout: self
          path: source

        # Turn this Powershell console into a developer powershell console.
        # https://intellitect.com/enter-vsdevshell-powershell/
        - pwsh: |
            $installPath = &"C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -latest -property installationpath
            $devShell    = &"C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe" -latest -find **\Microsoft.VisualStudio.DevShell.dll
            Import-Module $devShell
            Enter-VsDevShell -VsInstallPath $installPath -SkipAutomaticLocation -DevCmdArguments "-arch=amd64"
            $(Agent.BuildDirectory)/source/tools/build/binary-release/build-windows.ps1
          failOnStderr: false
          displayName: Run build script

        - publish: rakudo-win.zip
          artifact: rakudo-win
          
        - publish: rakudo-win.msi
          artifact: rakudo-win-msi

    - job: zip
      displayName: Package results
      dependsOn:
      - linux
      - macos
      - windows
      pool:
        vmImage: 'ubuntu-20.04'
      workspace:
        clean: all
      steps:
      - checkout: none

      - download: current
        artifact: rakudo-linux
        displayName: Download Linux build artifacts

      - download: current
        artifact: rakudo-macos
        displayName: Download MacOS build artifacts

      - download: current
        artifact: rakudo-win
        displayName: Download Windows binary build
        
      - download: current
        artifact: rakudo-win-msi
        displayName: Download Windows msi

      - script: |
          OUT_DIR=rakudo-builds-$(VERSION)-$(REVISION)
          mkdir $OUT_DIR
          cp $(Pipeline.Workspace)/rakudo-linux/rakudo-linux.tar.gz $OUT_DIR/rakudo-moar-$(VERSION)-$(REVISION)-linux-x86_64-gcc.tar.gz
          cp $(Pipeline.Workspace)/rakudo-macos/rakudo-macos.tar.gz $OUT_DIR/rakudo-moar-$(VERSION)-$(REVISION)-macos-x86_64-clang.tar.gz
          cp $(Pipeline.Workspace)/rakudo-win/rakudo-win.zip        $OUT_DIR/rakudo-moar-$(VERSION)-$(REVISION)-win-x86_64-msvc.zip
          cp $(Pipeline.Workspace)/rakudo-win-msi/rakudo-win.msi    $OUT_DIR/rakudo-moar-$(VERSION)-$(REVISION)-win-x86_64-msvc.msi
          tar -czf rakudo-moar-builds-$(VERSION)-$(REVISION).tar.gz $OUT_DIR

      - publish: rakudo-moar-builds-$(VERSION)-$(REVISION).tar.gz
        artifact: build-result
